AppSyncUrlSSMParameter:
  Type: AWS::SSM::Parameter
  Properties:
    Name: /${sls:stage}/${self:service}/app-sync-api-url
    Type: String
    Value: !GetAtt GraphQlApi.GraphQLUrl
AppSyncApiKeySSMParameter:
  Type: AWS::SSM::Parameter
  Properties:
    Name: /${sls:stage}/${self:service}/app-sync-api-key
    Type: String
    Value: !GetAtt GraphQlApiKeykey.ApiKey
CognitoUserPoolUrlSSMParameter:
  Type: AWS::SSM::Parameter
  Properties:
    Name: /${sls:stage}/${self:service}/cognito-user-pool-url
    Type: String
    Value:
      #/login?client_id=6bv8vp08h8rgcd7h1ersogdae&response_type=token&scope=email+openid+phone&redirect_uri=https%3A%2F%2Fwww.canada.ca
      !Join [
        "",
        [
          "https://",
          !Ref CognitoUserPoolDomain,
          ".auth.${aws:region}.amazoncognito.com",
          "/login?client_id=",
          !Ref CognitoUserPoolClient,
          "&response_type=token&scope=email+openid+phone&redirect_uri=",
          "${env:COGNITO_USER_POOL_CALLBACK_URL}",
        ],
      ]
CognitoUserPool:
  Type: AWS::Cognito::UserPool
  Properties:
    UsernameAttributes:
      - "email"
    UserPoolName: ${self:service}-${sls:stage}
    AutoVerifiedAttributes:
      - email
CognitoUserPoolClient:
  Type: AWS::Cognito::UserPoolClient
  Properties:
    ClientName: ${self:service}-${sls:stage}
    UserPoolId: !Ref CognitoUserPool
    AllowedOAuthFlowsUserPoolClient: true
    AccessTokenValidity: 24 # hours
    IdTokenValidity: 24 # hours
    SupportedIdentityProviders:
      - Google
      - COGNITO
    CallbackURLs:
      - ${env:COGNITO_USER_POOL_CALLBACK_URL}
    LogoutURLs:
      - ${env:COGNITO_USER_POOL_LOGOUT_URL}
    AllowedOAuthFlows:
      - implicit
    AllowedOAuthScopes:
      - phone
      - email
      - openid
CognitoUserPoolDomain:
  Type: AWS::Cognito::UserPoolDomain
  Properties:
    Domain: ${self:service}-${sls:stage}
    UserPoolId: !Ref CognitoUserPool
UserPoolIdentityProvider:
  Type: AWS::Cognito::UserPoolIdentityProvider
  Properties:
    ProviderName: Google
    ProviderType: Google
    UserPoolId: !Ref CognitoUserPool
    ProviderDetails:
      client_id: ${env:GOOGLE_CLIENT_ID}
      client_secret: ${env:GOOGLE_CLIENT_SECRET}
      authorize_scopes: profile email openid
    AttributeMapping:
      email: email
