service: stock-market-app
frameworkVersion: '3'

plugins:
  - serverless-appsync-plugin
  - serverless-appsync-simulator
  - serverless-offline
  - serverless-python-requirements

useDotenv: true

provider:
  name: aws
  runtime: python3.9
  environment:
    LOCAL_DEBUG: ${strToBool(${param:local_debug, 'false'})}
    ALPHAVANTAGE_API_KEY: ${env:ALPHAVANTAGE_API_KEY}

custom:
  pandasLambdaLayerMap:
    # Add a new reference if deploy in non us-east-1 region
    us-east-1: arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python39:3
  pythonRequirements:
    slim: true
    layer: true
  appSync: ${file(./appsync-conf.yml)}
  appsync-simulator:
    apiKey: 'da2-fakeApiId123456'
	
package:
  individually: false
  patterns:
    - '!**'
    - './src/**'

functions:
  getStockOverview:
    handler: src/handlers/stock_overview.handle_request
    layers:
      - Ref: PythonRequirementsLambdaLayer
      - ${self:custom.pandasLambdaLayerMap.${aws:region}}
  search:
    handler: src/handlers/search.handle_request
    layers:
      - Ref: PythonRequirementsLambdaLayer
      - ${self:custom.pandasLambdaLayerMap.${aws:region}}

resources:
  Resources: ${file(./resources.yml)}